def num(num, activity):
    print("The ants go marching {0} by {0}, hurrah! hurrah!".format(num))
    print("The ants go marching {0} by {0}, hurrah! hurrah!".format(num))
    print("The ants go marching {0} by {0},".format(num))
    print("The little one stops to {},".format(activity))
    print("And they all go marching down…")
    print("In the ground…")
    print("To get out…")
    print("Of the rain.")
    print("Boom! Boom! Boom!")

def main():
    print("\n")
    num("one", "suck his thumb")
    num("two", "tie his shoe")
    num("three", "climb a tree")
    num("four", "rest some more")
    num("five", "talk some jive")
    num("six", "pick up sticks")
    num("seven", "pray to heaven")
    num("eight", "masturbate")
    num("nine", "wail and whine")
    num("ten", "get his ken")
    print("\n")
main()
