from graphics import *

def main():
    win = GraphWin("Archery", 500, 500)
    win.setBackground(color_rgb(128,128,128))
    win.setCoords(0.0, 0.0, 5.0, 5.0)
    p = Point(2.5,2.5)
    c0 = Circle(p, 2.5)
    c0.setFill("white")
    c0.setOutline("white")
    c0.draw(win)
    c1 = Circle(p, 2.0)
    c1.setFill("black")
    c1.setOutline("black")
    c1.draw(win)
    c2 = Circle(p, 1.5)
    c2.setFill("blue")
    c2.setOutline("blue")
    c2.draw(win)
    c3 = Circle(p, 1.0)
    c3.setFill("red")
    c3.setOutline("red")
    c3.draw(win)
    c4 = Circle(p, 0.5)
    c4.setFill("yellow")
    c4.setOutline("yellow")
    c4.draw(win)
    win.getMouse()
    win.close()
main()
