# True/False

# 1. False, could also be in single quotes
# 2. True
# 3. False, can contain any sequence of characters
# 4. True
# 5. True
# 6. True
# 7. True
# 8. False, that's far too easy to break
# 9. False, use "append". Add is for sets
# 10. False, use "open"

# Multiple Choice

# 1. d) indexing
# 2. c) s[:len(s)-1]
# 3. a) ord, it gives the unicode *value*
# 4. c) str
# 5. c) Unicode
# 6. d) upper
# 7. d) {}
# 8. c) readall
# 9. c) batch
# 10. a) open

s1 = "spam"
s2 = "ni!"

# 1. Show the results of evaluating each of the following string expressions

# (a)
print("The knights who say, " + s2)

# (b)
print(3 * s1 + 2 * s2)

# (c)
print(s1[1])

# (d)
print(s1[1:3])

# (e)
print(s1[2] + s2[:2])

# (f)
print(s1 + s2[-1])

# (g)
print(s1.upper())

# (g)
print(s1.upper().ljust(4) * 3)

# 2. Show an expression that constructs the following

# (a) "NI!"
print(s2.upper())

# (b) "ni!spamni!"
print(s2 + s1 + s2)

# (c) "Spam Ni!  Spam Ni!  Spam Ni!"
print((s1.title() + " " + s2.title()).ljust(9) + (s1.title() + " " + s2.title()).center(9) + (s1.title() + " " + s2.title()).rjust(10))

# (d) "spam"
print(s1)

# (e) ["sp", "m"]
print([s1[:2],s1[3:]])

# (f) "spm"
print(s1[:2]+s1[3:])

# 3. Show the output generated by the following

# (a)
for ch in "aardvark":
    print(ch)

# (b)
for w in "Now is the winter of our discontent...".split():
    print(w)

# (c)
for w in "Mississippi".split("i"):
    print(w)

# (d)
msg = ""
for s in "secret".split("e"):
    msg = msg + s
print(msg)

# (e)
msg = ""
for ch in "secret":
    msg = msg + chr(ord(ch)+1)
print(msg)

# 4. Show the string that would follow

# (a)
print("Looks like {1} and {0} for breakfast".format("eggs", "spam"))

# (b)
print("There is {0} {1} {2} {3}".format(1, "spam", 4, "you"))

# (c)
print("Hello {0}".format("Susan", "Computewell"))

# (d)
print("{0:0.2f} {0:0.2f}".format(2.3, 2.3468))

# (e)
#print("{7.5f} {7.5f}".format(2.3, 2.3468))

# (f)
print("Time left {0:02}:{1:05.2f}".format(1, 37.374))

# (g)
#print("{1:3}".format("14"))

# 5. Public key encryption can be used for identifying and decoding publicly. Private keys use the same key for encrypting and decrypting messages, and those have to be kept secret from everyone. But But public keys are meant to shared and private keys can be kept to decode messages written with the public key. The internet is simply made up of communications between pairs of people. Securely communicating is possible if keys are used.
